%{!?__python3: %global __python3 /usr/bin/python3}
%{!?python3_sitelib: %global python3_sitelib %(%{__python3} -c "import sysconfig; print(sysconfig.get_path('purelib'))")}

%define base_name gfal
%define dist_name gfal

Name: python3-%{base_name}
Version: %{pkg_version}
Release: %{pkg_release}%{?dist}
Summary: GFAL-compatible command-line tools and Python library for remote storage
License: BSD-3-Clause
URL: https://github.com/lobis/gfal
Source0: %{dist_name}-%{version}-py3-none-any.whl

BuildRequires: python3-devel
BuildRequires: python3-pip

# Runtime dependencies available in EPEL / base RHEL
Requires: xrootd-client
Requires: xrdcl-http
Requires: python3-aiohttp
Requires: python3-rich
Requires: python3-click
Requires: bash-completion
# python3-fsspec is available in EPEL 10+ but not EPEL 9 — handled conditionally below.
%if 0%{?rhel} >= 10
Requires: python3-fsspec
%endif
# Note: python3-rich-click is intentionally not required here. It is an
#       optional runtime enhancement in the Python package, and gfal falls
#       back to plain click when it is not installed.
AutoReq: no
AutoProv: no

%description
gfal provides GFAL-compatible command-line tools and a Python library for local
and remote storage. The transitional xrdfs backend delegates core remote read
and metadata commands to the operating system's XRootD client; commands not yet
migrated retain the previous Python implementation.

%prep
# Nothing to prep for a pre-built wheel

%build
# Nothing to build for a pre-built wheel

%install
# Install gfal itself (no deps — all declared as Requires or bundled below)
%{__python3} -m pip install \
    --root %{buildroot} \
    --prefix /usr \
    --no-deps \
    --no-build-isolation \
    --no-cache-dir \
    %{_sourcedir}/%{dist_name}-%{version}-py3-none-any.whl

%if 0%{?rhel} < 10
# Bundle fsspec on RHEL/EL9 where it is not available in EPEL
%{__python3} -m pip install \
    --root %{buildroot} \
    --prefix /usr \
    --no-build-isolation \
    --no-cache-dir \
    "fsspec>=2023.1.0"
%endif

# Bundle the PyPI XRootD bindings because EPEL currently provides XRootD 5.x
# while gfal requires the Python bindings starting at 6.0.1.
%{__python3} -m pip install \
    --root %{buildroot} \
    --prefix /usr \
    --no-build-isolation \
    --no-cache-dir \
    "xrootd>=6.0.1"

# Install pre-generated shell completion scripts (generated by make prepare)
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions
mkdir -p %{buildroot}%{_datadir}/zsh/site-functions
install -m 644 %{_sourcedir}/gfal.bash-completion %{buildroot}%{_datadir}/bash-completion/completions/gfal
install -m 644 %{_sourcedir}/_gfal.zsh-completion %{buildroot}%{_datadir}/zsh/site-functions/_gfal

%files
%{python3_sitelib}/gfal/
%{python3_sitelib}/gfal-*.dist-info/
%if 0%{?rhel} < 10
%{python3_sitelib}/fsspec/
%{python3_sitelib}/fsspec-*.dist-info/
%endif
%{python3_sitearch}/XRootD/
%{python3_sitearch}/pyxrootd/
%{python3_sitearch}/xrootd.libs/
%{python3_sitearch}/xrootd-*.dist-info/
%{_bindir}/gfal
%{_datadir}/bash-completion/completions/gfal
%{_datadir}/zsh/site-functions/_gfal

%changelog -f %{_sourcedir}/CHANGELOG
