zookeeper:
  embedded: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false

dcache:
  spacemanager:
    enabled: false
  pools:
    - a

services:
  nfs:
    enabled: false
  dcap:
    enabled: false
  dcapg:
    enabled: false
  xrootdg:
    enabled: false
  webdav:
    enabled: false
  webdavs:
    enabled: true
  srm:
    enabled: false
  gridftp:
    enabled: false
  sshAdmin:
    enabled: false
  frontend:
    enabled: false
  frontends:
    enabled: false
